### ISSUE TITLE
Raspbian Linux - no display?

### ISSUE THREAD

**Issue by LameLefty** [Ho-Ro/openhantek#2]
I built your fork tonight on my Raspberry Pi 3B. I have both channel probes connected to the 6022BE calibration source. However, when I run the program, the display remains empty. By contrast, the most recent base OpenHantek, running on the same hardware, shows the calibration square waves as expected and as per normal. 

Any idea why your fork does not show a visible waveform while the base OpenHantek does?

**Comment by Ho-Ro** [comment]
Maybe it depends on the glscope.cpp change of patch 97540dfc that I implemented according
https://github.com/OpenHantek/openhantek/issues/221#issuecomment-462728423
Please revert and try again. 
Other option is to call "Openhantek --useGLES".

**Comment by LameLefty** [comment]
The "--useGLES" option did the trick. Thank you. I forget I have to that with the base OpenHantek as well on my RPi. I have a desktop shortcut setup and forgot I had this option in the startup command.

**Comment by Ho-Ro** [comment]
Thx - good to know I didn't implement a regression.
