### ISSUE TITLE
Unable to install from deb, "invalid character in version number"

### ISSUE THREAD

**Issue by raleighlittles** [Ho-Ro/openhantek#3]
First off thanks for maintaining this project.

I'm having an issue installing the debian packages on my Ubuntu 18.10 system. The debians were downloaded from your Releases page. Here's the error I got on the two that I tested:

```
raleigh@raleigh-Z170X-UD5:~/Downloads$ sudo dpkg -i openhantek-20190308_b7da4e8-1_amd64.deb 
[sudo] password for raleigh: 
dpkg: error processing archive openhantek-20190308_b7da4e8-1_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 8 package 'openhantek':
 error in 'Version' field string '20190308_b7da4e8': invalid character in version number
Errors were encountered while processing:
 openhantek-20190308_b7da4e8-1_amd64.deb
raleigh@raleigh-Z170X-UD5:~/Downloads$ sudo dpkg -i openhantek-20190307_665682e-1_amd64.deb 
dpkg: error processing archive openhantek-20190307_665682e-1_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 8 package 'openhantek':
 error in 'Version' field string '20190307_665682e': invalid character in version number
Errors were encountered while processing:
 openhantek-20190307_665682e-1_amd64.deb
```

**Comment by raleighlittles** [comment]
Additionally, here's my system information:

```
Linux raleigh-Z170X-UD5 4.18.0-15-generic #16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
```

**Comment by Ho-Ro** [comment]
Hi Raleigh, 
Thx for opening this issue. Please check latest alpha-13 release https://github.com/Ho-Ro/openhantek/releases/tag/v2.0-alpha-13 that installs flawlessly on my debian buster system.
I am particularly interested in whether the dependencies match the ubuntu package names. The pre-built  Travis packages were built on xenial.
Martin

**Comment by raleighlittles** [comment]
Hey thank you for responding so quickly! 

Your latest alpha release installed successfully on my system. I did run into an issue with dependencies at first:

```
 sudo dpkg -i openhantek_20190309-1_amd64.deb                                                2191ms  Sat 09 Mar 2019 11:41:54 AM PST
(Reading database ... 568424 files and directories currently installed.)
Preparing to unpack openhantek_20190309-1_amd64.deb ...
Unpacking openhantek (20190309) over (20190309) ...
dpkg: dependency problems prevent configuration of openhantek:
 openhantek depends on libfftw3-3; however:
  Package libfftw3-3 is not installed.

dpkg: error processing package openhantek (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 openhantek

```

But that was resolved by simply installing that particular dependency that was missing (`libfftw3-3`). 

After that it installed correctly
```
 sudo dpkg -i openhantek_20190309-1_amd64.deb                                                 17.1s  Sat 09 Mar 2019 11:43:02 AM PST
(Reading database ... 568442 files and directories currently installed.)
Preparing to unpack openhantek_20190309-1_amd64.deb ...
Unpacking openhantek (20190309) over (20190309) ...
Setting up openhantek (20190309) ...

```

Thanks again for maintaining this project. I'll mark the issue as closed now  :+1:

**Comment by Ho-Ro** [comment]
Hi Raleigh, 
Good it works for you. If a package doesn't install properly due to missing dependencies the simplest way to solve it is calling `(sudo) apt -f install` - no need to install all missing packages by hand. Option -f means *fix* pending installs and it pull in all missing packages and finally configures *your* package. 
Martin

EDIT: 
You can even save a step by installing downloaded packages with apt and it will install dependencies at the same time. Go to the directory where you downloaded the package:
`sudo apt install ./downloaded_package.deb`
