### ISSUE TITLE
Cannot set cursors when measurement is paused

### ISSUE THREAD

**Issue by ngreve** [Ho-Ro/openhantek#8]
Cannot set any cursor of any channel when measurement is paused. When pressed 'play' again, the cursor appears suddenly as drawn in paused mode.

**Comment by Ho-Ro** [comment]
That's normal behavior right now. *Pause* stops any display update -> also cursor drawing is delayed.

**Comment by Ho-Ro** [comment]
Fixed by cb5474a (that was an easy fix) - thx for nudging me ;)
